version: '3.8'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    ports:
      - '8080:3000'
    command: npm run start:dev

  mysql:
    image: mysql:5.7
    ports:
      - '36000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
